global_costmap:
  global_frame: map
  robot_base_frame: mob_rob/base_link
  static_map: true
  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  static_layer:
    map_topic: /mob_rob/map